/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdio.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_sl_string__initialize_successful(void);
extern void test_sl_string__initialize_unsuccessful_null_mem(void);
extern void test_sl_string__initialize_unsuccessful_mem_size_zero(void);
extern void test_sl_string__initialize_from_successful(void);
extern void test_sl_string__initialize_from_null_init_string(void);
extern void test_sl_string__initialize_from_null_string_memory(void);
extern void test_sl_string__get_capacity(void);
extern void test_sl_string__is_full(void);
extern void test_sl_string__get_length_empty_string(void);
extern void test_sl_string__get_length_non_empty_string(void);
extern void test_sl_string__c_str_empty_string(void);
extern void test_sl_string__c_str_non_empty_string(void);
extern void test_append_char(void);
extern void test_sl_string__to_int_successful(void);
extern void test_sl_string__to_int_unsuccessful_contains_non_int_chars(void);
extern void test_sl_string__to_int_unsuccessful_empty_string(void);
extern void test_sl_string__to_float_successful(void);
extern void test_sl_string__to_float_unsuccessful_contains_non_float_chars(void);
extern void test_sl_string__to_float_unsuccessful_empty_string(void);
extern void test_sl_string__is_alpha_contains_only_alpha_chars(void);
extern void test_sl_string__is_alpha_contains_non_alpha_chars(void);
extern void test_sl_string__is_alpha_empty_string(void);
extern void test_sl_string__is_alphanum_successful(void);
extern void test_sl_string__is_alphanum_contains_non_alphanum_chars(void);
extern void test_sl_string__is_alphanum_empty_string(void);
extern void test_sl_string__clear(void);
extern void test_sl_string__clear_all_memory(void);
extern void test_sl_string__to_lower(void);
extern void test_sl_string__to_upper(void);
extern void test_sl_string__printf_successful(void);
extern void test_sl_string__printf_with_string_size_zero(void);
extern void test_sl_string__printf_append_with_string_size_zero(void);
extern void test_sl_string__printf_filename_format(void);
extern void test_sl_string__scanf_with_arg_size_zero(void);
extern void test_sl_string__printf_truncated(void);
extern void test_sl_string__printf_append_successful(void);
extern void test_sl_string__printf_append_truncated(void);
extern void test_sl_string__scanf_successful(void);
extern void test_sl_string__tokenize_successful(void);
extern void test_sl_string__tokenize_unsuccessful_null_delimiter(void);
extern void test_sl_string__tokenize_null_args(void);
extern void test_sl_string__tokenize_mismatch_of_ptrs_and_num_of_tokens(void);
extern void test_sl_string__set(void);
extern void test_sl_string__insert_at_success(void);
extern void test_sl_string__insert_at_pos_out_of_bounds(void);
extern void test_sl_string__insert_at_string_is_null(void);
extern void test_sl_string__insert_at_capacity_reached(void);
extern void test_sl_string__append_successful(void);
extern void test_sl_string__append_string_is_null(void);
extern void test_sl_string__append_capacity_reached(void);
extern void test_sl_string__equals_to_successful(void);
extern void test_sl_string__equals_to_unsuccessful_strings_dont_match(void);
extern void test_sl_string__equals_to_unsuccessful_null_substring(void);
extern void test_sl_string__equals_to_ignore_case_successful(void);
extern void test_sl_string__equals_to_ignore_case_unsuccessful_strings_dont_match(void);
extern void test_sl_string__equals_to_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__last_index_of_found(void);
extern void test_sl_string__last_index_of_unsuccessful_not_found(void);
extern void test_sl_string__last_index_of_unsuccessful_null_substring(void);
extern void test_sl_string__last_index_of_ignore_case_found(void);
extern void test_sl_string_last_index_of_ignore_lower_case(void);
extern void test_sl_string_last_index_of_ignore_multiple_sub_string(void);
extern void test_sl_string__last_index_of_ignore_case_not_found(void);
extern void test_sl_string__last_index_of_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__first_index_of_found(void);
extern void test_sl_string__first_index_of_unsuccessful_not_found(void);
extern void test_sl_string__first_index_of_unsuccessful_null_substring(void);
extern void test_sl_string__first_index_of_ignore_case_found(void);
extern void test_sl_string__first_index_of_ignore_case_not_found(void);
extern void test_sl_string__first_index_of_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string_first_index_of_ignore_lower_case(void);
extern void test_sl_string__contains_found(void);
extern void test_sl_string__contains_unsuccessful_not_found(void);
extern void test_sl_string__contains_unsuccessful_null_substring(void);
extern void test_sl_string__contains_ignore_case_found(void);
extern void test_sl_string__contains_ignore_case_not_found(void);
extern void test_sl_string__contains_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__count_of_successful(void);
extern void test_sl_string__count_of_no_occurance(void);
extern void test_sl_string__count_of_unsuccessful_null_substring(void);
extern void test_sl_string__begins_with_found(void);
extern void test_sl_string__begins_with_unsuccessful_not_found(void);
extern void test_sl_string__begins_with_unsuccessful_null_substring(void);
extern void test_sl_string__begins_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_limited_chars(void);
extern void test_sl_string__begins_with_ignore_case_found(void);
extern void test_sl_string__begins_with_ignore_case_not_found(void);
extern void test_sl_string__begins_with_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__begins_ignore_case_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_whole_word_found(void);
extern void test_sl_string__begins_with_whole_word_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_whole_word_not_matching(void);
extern void test_sl_string__begins_with_whole_word_string_ends_with_null(void);
extern void test_sl_string__begins_with_whole_word_unsuccessful_not_found(void);
extern void test_sl_string__begins_with_whole_word_unsuccessful_null_params(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_found(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_not_found(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_null_params(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_not_matching(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_string_delimeter_null(void);
extern void test_sl_string__ends_with_found(void);
extern void test_sl_string__ends_with_unsuccessful_large_substring(void);
extern void test_sl_string__ends_with_unsuccessful_not_found(void);
extern void test_sl_string__ends_with_unsuccessful_null_substring(void);
extern void test_sl_string__ends_newline(void);
extern void test_sl_string__ends_with_ignore_case_found(void);
extern void test_sl_string__ends_with_ignore_case_unsuccessful_large_substring(void);
extern void test_sl_string__ends_with_ignore_case_not_found(void);
extern void test_sl_string__ends_with_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__erase_successful(void);
extern void test_sl_string__erase_null_substring(void);
extern void test_sl_string__erase_substring_not_found(void);
extern void test_sl_string__erase_first_successful(void);
extern void test_sl_string__erase_first_n_chars_longer_than_string(void);
extern void test_sl_string__erase_last_successful(void);
extern void test_sl_string__erase_last_n_chars_longer_than_string(void);
extern void test_sl_string__erase_at_successful(void);
extern void test_sl_string__erase_at_index_out_of_bounds(void);
extern void test_sl_string__erase_after_successful(void);
extern void test_sl_string__erase_after_index_out_of_bounds(void);
extern void test_sl_string__erase_after_n_chars_longer_than_string(void);
extern void test_sl_string__erase_after_string(void);
extern void test_sl_string__erase_first_word_successful(void);
extern void test_sl_string__erase_first_word_no_words(void);
extern void test_sl_string__erase_special_chars_successful(void);
extern void test_sl_string__erase_special_chars_no_special_chars(void);
extern void test_erase_int(void);
extern void test_sl_string__trim_end_successful(void);
extern void test_sl_string__trim_end_null_chars_to_trim(void);
extern void test_sl_string__trim_end_chars_not_found(void);
extern void test_sl_string__trim_start_successful(void);
extern void test_sl_string__trim_start_null_chars_to_trim(void);
extern void test_sl_string__trim_start_chars_not_found(void);
extern void test_sl_string__replace_first_successful(void);
extern void test_sl_string__replace_first_null_params(void);
extern void test_sl_string__replace_first_substring_not_found(void);
extern void test_sl_string__replace_first_empty_string_and_replace_string(void);
extern void test_sl_string__replace_last_successful(void);
extern void test_sl_string__replace_last_null_params(void);
extern void test_sl_string__replace_last_substring_not_found(void);
extern void test_sl_string__replace_all_successful(void);
extern void test_sl_string__replace_all_null_params(void);
extern void test_sl_string__replace_all_substring_not_found(void);
extern void test_sl_string__replace_all_double_slash_with_slash(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("projects\\lpc40xx_freertos\\l2_utils\\string\\test\\test_sl_string.c");
  run_test(test_sl_string__initialize_successful, "test_sl_string__initialize_successful", 87);
  run_test(test_sl_string__initialize_unsuccessful_null_mem, "test_sl_string__initialize_unsuccessful_null_mem", 93);
  run_test(test_sl_string__initialize_unsuccessful_mem_size_zero, "test_sl_string__initialize_unsuccessful_mem_size_zero", 100);
  run_test(test_sl_string__initialize_from_successful, "test_sl_string__initialize_from_successful", 106);
  run_test(test_sl_string__initialize_from_null_init_string, "test_sl_string__initialize_from_null_init_string", 117);
  run_test(test_sl_string__initialize_from_null_string_memory, "test_sl_string__initialize_from_null_string_memory", 127);
  run_test(test_sl_string__get_capacity, "test_sl_string__get_capacity", 134);
  run_test(test_sl_string__is_full, "test_sl_string__is_full", 140);
  run_test(test_sl_string__get_length_empty_string, "test_sl_string__get_length_empty_string", 151);
  run_test(test_sl_string__get_length_non_empty_string, "test_sl_string__get_length_non_empty_string", 155);
  run_test(test_sl_string__c_str_empty_string, "test_sl_string__c_str_empty_string", 162);
  run_test(test_sl_string__c_str_non_empty_string, "test_sl_string__c_str_non_empty_string", 167);
  run_test(test_append_char, "test_append_char", 175);
  run_test(test_sl_string__to_int_successful, "test_sl_string__to_int_successful", 198);
  run_test(test_sl_string__to_int_unsuccessful_contains_non_int_chars, "test_sl_string__to_int_unsuccessful_contains_non_int_chars", 208);
  run_test(test_sl_string__to_int_unsuccessful_empty_string, "test_sl_string__to_int_unsuccessful_empty_string", 222);
  run_test(test_sl_string__to_float_successful, "test_sl_string__to_float_successful", 226);
  run_test(test_sl_string__to_float_unsuccessful_contains_non_float_chars, "test_sl_string__to_float_unsuccessful_contains_non_float_chars", 240);
  run_test(test_sl_string__to_float_unsuccessful_empty_string, "test_sl_string__to_float_unsuccessful_empty_string", 254);
  run_test(test_sl_string__is_alpha_contains_only_alpha_chars, "test_sl_string__is_alpha_contains_only_alpha_chars", 258);
  run_test(test_sl_string__is_alpha_contains_non_alpha_chars, "test_sl_string__is_alpha_contains_non_alpha_chars", 263);
  run_test(test_sl_string__is_alpha_empty_string, "test_sl_string__is_alpha_empty_string", 268);
  run_test(test_sl_string__is_alphanum_successful, "test_sl_string__is_alphanum_successful", 272);
  run_test(test_sl_string__is_alphanum_contains_non_alphanum_chars, "test_sl_string__is_alphanum_contains_non_alphanum_chars", 286);
  run_test(test_sl_string__is_alphanum_empty_string, "test_sl_string__is_alphanum_empty_string", 292);
  run_test(test_sl_string__clear, "test_sl_string__clear", 296);
  run_test(test_sl_string__clear_all_memory, "test_sl_string__clear_all_memory", 304);
  run_test(test_sl_string__to_lower, "test_sl_string__to_lower", 317);
  run_test(test_sl_string__to_upper, "test_sl_string__to_upper", 323);
  run_test(test_sl_string__printf_successful, "test_sl_string__printf_successful", 329);
  run_test(test_sl_string__printf_with_string_size_zero, "test_sl_string__printf_with_string_size_zero", 338);
  run_test(test_sl_string__printf_append_with_string_size_zero, "test_sl_string__printf_append_with_string_size_zero", 345);
  run_test(test_sl_string__printf_filename_format, "test_sl_string__printf_filename_format", 352);
  run_test(test_sl_string__scanf_with_arg_size_zero, "test_sl_string__scanf_with_arg_size_zero", 365);
  run_test(test_sl_string__printf_truncated, "test_sl_string__printf_truncated", 373);
  run_test(test_sl_string__printf_append_successful, "test_sl_string__printf_append_successful", 389);
  run_test(test_sl_string__printf_append_truncated, "test_sl_string__printf_append_truncated", 400);
  run_test(test_sl_string__scanf_successful, "test_sl_string__scanf_successful", 423);
  run_test(test_sl_string__tokenize_successful, "test_sl_string__tokenize_successful", 438);
  run_test(test_sl_string__tokenize_unsuccessful_null_delimiter, "test_sl_string__tokenize_unsuccessful_null_delimiter", 453);
  run_test(test_sl_string__tokenize_null_args, "test_sl_string__tokenize_null_args", 468);
  run_test(test_sl_string__tokenize_mismatch_of_ptrs_and_num_of_tokens, "test_sl_string__tokenize_mismatch_of_ptrs_and_num_of_tokens", 473);
  run_test(test_sl_string__set, "test_sl_string__set", 487);
  run_test(test_sl_string__insert_at_success, "test_sl_string__insert_at_success", 503);
  run_test(test_sl_string__insert_at_pos_out_of_bounds, "test_sl_string__insert_at_pos_out_of_bounds", 509);
  run_test(test_sl_string__insert_at_string_is_null, "test_sl_string__insert_at_string_is_null", 516);
  run_test(test_sl_string__insert_at_capacity_reached, "test_sl_string__insert_at_capacity_reached", 522);
  run_test(test_sl_string__append_successful, "test_sl_string__append_successful", 528);
  run_test(test_sl_string__append_string_is_null, "test_sl_string__append_string_is_null", 534);
  run_test(test_sl_string__append_capacity_reached, "test_sl_string__append_capacity_reached", 540);
  run_test(test_sl_string__equals_to_successful, "test_sl_string__equals_to_successful", 546);
  run_test(test_sl_string__equals_to_unsuccessful_strings_dont_match, "test_sl_string__equals_to_unsuccessful_strings_dont_match", 551);
  run_test(test_sl_string__equals_to_unsuccessful_null_substring, "test_sl_string__equals_to_unsuccessful_null_substring", 556);
  run_test(test_sl_string__equals_to_ignore_case_successful, "test_sl_string__equals_to_ignore_case_successful", 561);
  run_test(test_sl_string__equals_to_ignore_case_unsuccessful_strings_dont_match, "test_sl_string__equals_to_ignore_case_unsuccessful_strings_dont_match", 567);
  run_test(test_sl_string__equals_to_ignore_case_unsuccessful_null_substring, "test_sl_string__equals_to_ignore_case_unsuccessful_null_substring", 573);
  run_test(test_sl_string__last_index_of_found, "test_sl_string__last_index_of_found", 578);
  run_test(test_sl_string__last_index_of_unsuccessful_not_found, "test_sl_string__last_index_of_unsuccessful_not_found", 583);
  run_test(test_sl_string__last_index_of_unsuccessful_null_substring, "test_sl_string__last_index_of_unsuccessful_null_substring", 588);
  run_test(test_sl_string__last_index_of_ignore_case_found, "test_sl_string__last_index_of_ignore_case_found", 593);
  run_test(test_sl_string_last_index_of_ignore_lower_case, "test_sl_string_last_index_of_ignore_lower_case", 603);
  run_test(test_sl_string_last_index_of_ignore_multiple_sub_string, "test_sl_string_last_index_of_ignore_multiple_sub_string", 608);
  run_test(test_sl_string__last_index_of_ignore_case_not_found, "test_sl_string__last_index_of_ignore_case_not_found", 613);
  run_test(test_sl_string__last_index_of_ignore_case_unsuccessful_null_substring, "test_sl_string__last_index_of_ignore_case_unsuccessful_null_substring", 617);
  run_test(test_sl_string__first_index_of_found, "test_sl_string__first_index_of_found", 623);
  run_test(test_sl_string__first_index_of_unsuccessful_not_found, "test_sl_string__first_index_of_unsuccessful_not_found", 633);
  run_test(test_sl_string__first_index_of_unsuccessful_null_substring, "test_sl_string__first_index_of_unsuccessful_null_substring", 638);
  run_test(test_sl_string__first_index_of_ignore_case_found, "test_sl_string__first_index_of_ignore_case_found", 643);
  run_test(test_sl_string__first_index_of_ignore_case_not_found, "test_sl_string__first_index_of_ignore_case_not_found", 653);
  run_test(test_sl_string__first_index_of_ignore_case_unsuccessful_null_substring, "test_sl_string__first_index_of_ignore_case_unsuccessful_null_substring", 658);
  run_test(test_sl_string_first_index_of_ignore_lower_case, "test_sl_string_first_index_of_ignore_lower_case", 664);
  run_test(test_sl_string__contains_found, "test_sl_string__contains_found", 669);
  run_test(test_sl_string__contains_unsuccessful_not_found, "test_sl_string__contains_unsuccessful_not_found", 674);
  run_test(test_sl_string__contains_unsuccessful_null_substring, "test_sl_string__contains_unsuccessful_null_substring", 679);
  run_test(test_sl_string__contains_ignore_case_found, "test_sl_string__contains_ignore_case_found", 684);
  run_test(test_sl_string__contains_ignore_case_not_found, "test_sl_string__contains_ignore_case_not_found", 689);
  run_test(test_sl_string__contains_ignore_case_unsuccessful_null_substring, "test_sl_string__contains_ignore_case_unsuccessful_null_substring", 694);
  run_test(test_sl_string__count_of_successful, "test_sl_string__count_of_successful", 699);
  run_test(test_sl_string__count_of_no_occurance, "test_sl_string__count_of_no_occurance", 704);
  run_test(test_sl_string__count_of_unsuccessful_null_substring, "test_sl_string__count_of_unsuccessful_null_substring", 709);
  run_test(test_sl_string__begins_with_found, "test_sl_string__begins_with_found", 714);
  run_test(test_sl_string__begins_with_unsuccessful_not_found, "test_sl_string__begins_with_unsuccessful_not_found", 719);
  run_test(test_sl_string__begins_with_unsuccessful_null_substring, "test_sl_string__begins_with_unsuccessful_null_substring", 724);
  run_test(test_sl_string__begins_unsuccessful_large_substring, "test_sl_string__begins_unsuccessful_large_substring", 729);
  run_test(test_sl_string__begins_with_limited_chars, "test_sl_string__begins_with_limited_chars", 734);
  run_test(test_sl_string__begins_with_ignore_case_found, "test_sl_string__begins_with_ignore_case_found", 750);
  run_test(test_sl_string__begins_with_ignore_case_not_found, "test_sl_string__begins_with_ignore_case_not_found", 755);
  run_test(test_sl_string__begins_with_ignore_case_unsuccessful_null_substring, "test_sl_string__begins_with_ignore_case_unsuccessful_null_substring", 760);
  run_test(test_sl_string__begins_ignore_case_unsuccessful_large_substring, "test_sl_string__begins_ignore_case_unsuccessful_large_substring", 765);
  run_test(test_sl_string__begins_with_whole_word_found, "test_sl_string__begins_with_whole_word_found", 770);
  run_test(test_sl_string__begins_with_whole_word_unsuccessful_large_substring, "test_sl_string__begins_with_whole_word_unsuccessful_large_substring", 780);
  run_test(test_sl_string__begins_with_whole_word_not_matching, "test_sl_string__begins_with_whole_word_not_matching", 785);
  run_test(test_sl_string__begins_with_whole_word_string_ends_with_null, "test_sl_string__begins_with_whole_word_string_ends_with_null", 790);
  run_test(test_sl_string__begins_with_whole_word_unsuccessful_not_found, "test_sl_string__begins_with_whole_word_unsuccessful_not_found", 795);
  run_test(test_sl_string__begins_with_whole_word_unsuccessful_null_params, "test_sl_string__begins_with_whole_word_unsuccessful_null_params", 800);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_found, "test_sl_string__begins_with_whole_word_ignore_case_found", 807);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_not_found, "test_sl_string__begins_with_whole_word_ignore_case_not_found", 819);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_null_params, "test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_null_params", 825);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_large_substring, "test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_large_substring", 835);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_not_matching, "test_sl_string__begins_with_whole_word_ignore_case_not_matching", 842);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_string_delimeter_null, "test_sl_string__begins_with_whole_word_ignore_case_string_delimeter_null", 848);
  run_test(test_sl_string__ends_with_found, "test_sl_string__ends_with_found", 855);
  run_test(test_sl_string__ends_with_unsuccessful_large_substring, "test_sl_string__ends_with_unsuccessful_large_substring", 860);
  run_test(test_sl_string__ends_with_unsuccessful_not_found, "test_sl_string__ends_with_unsuccessful_not_found", 865);
  run_test(test_sl_string__ends_with_unsuccessful_null_substring, "test_sl_string__ends_with_unsuccessful_null_substring", 870);
  run_test(test_sl_string__ends_newline, "test_sl_string__ends_newline", 875);
  run_test(test_sl_string__ends_with_ignore_case_found, "test_sl_string__ends_with_ignore_case_found", 889);
  run_test(test_sl_string__ends_with_ignore_case_unsuccessful_large_substring, "test_sl_string__ends_with_ignore_case_unsuccessful_large_substring", 895);
  run_test(test_sl_string__ends_with_ignore_case_not_found, "test_sl_string__ends_with_ignore_case_not_found", 901);
  run_test(test_sl_string__ends_with_ignore_case_unsuccessful_null_substring, "test_sl_string__ends_with_ignore_case_unsuccessful_null_substring", 907);
  run_test(test_sl_string__erase_successful, "test_sl_string__erase_successful", 913);
  run_test(test_sl_string__erase_null_substring, "test_sl_string__erase_null_substring", 920);
  run_test(test_sl_string__erase_substring_not_found, "test_sl_string__erase_substring_not_found", 927);
  run_test(test_sl_string__erase_first_successful, "test_sl_string__erase_first_successful", 934);
  run_test(test_sl_string__erase_first_n_chars_longer_than_string, "test_sl_string__erase_first_n_chars_longer_than_string", 941);
  run_test(test_sl_string__erase_last_successful, "test_sl_string__erase_last_successful", 948);
  run_test(test_sl_string__erase_last_n_chars_longer_than_string, "test_sl_string__erase_last_n_chars_longer_than_string", 955);
  run_test(test_sl_string__erase_at_successful, "test_sl_string__erase_at_successful", 962);
  run_test(test_sl_string__erase_at_index_out_of_bounds, "test_sl_string__erase_at_index_out_of_bounds", 969);
  run_test(test_sl_string__erase_after_successful, "test_sl_string__erase_after_successful", 976);
  run_test(test_sl_string__erase_after_index_out_of_bounds, "test_sl_string__erase_after_index_out_of_bounds", 983);
  run_test(test_sl_string__erase_after_n_chars_longer_than_string, "test_sl_string__erase_after_n_chars_longer_than_string", 991);
  run_test(test_sl_string__erase_after_string, "test_sl_string__erase_after_string", 999);
  run_test(test_sl_string__erase_first_word_successful, "test_sl_string__erase_first_word_successful", 1009);
  run_test(test_sl_string__erase_first_word_no_words, "test_sl_string__erase_first_word_no_words", 1016);
  run_test(test_sl_string__erase_special_chars_successful, "test_sl_string__erase_special_chars_successful", 1023);
  run_test(test_sl_string__erase_special_chars_no_special_chars, "test_sl_string__erase_special_chars_no_special_chars", 1030);
  run_test(test_erase_int, "test_erase_int", 1037);
  run_test(test_sl_string__trim_end_successful, "test_sl_string__trim_end_successful", 1065);
  run_test(test_sl_string__trim_end_null_chars_to_trim, "test_sl_string__trim_end_null_chars_to_trim", 1072);
  run_test(test_sl_string__trim_end_chars_not_found, "test_sl_string__trim_end_chars_not_found", 1079);
  run_test(test_sl_string__trim_start_successful, "test_sl_string__trim_start_successful", 1086);
  run_test(test_sl_string__trim_start_null_chars_to_trim, "test_sl_string__trim_start_null_chars_to_trim", 1096);
  run_test(test_sl_string__trim_start_chars_not_found, "test_sl_string__trim_start_chars_not_found", 1103);
  run_test(test_sl_string__replace_first_successful, "test_sl_string__replace_first_successful", 1110);
  run_test(test_sl_string__replace_first_null_params, "test_sl_string__replace_first_null_params", 1117);
  run_test(test_sl_string__replace_first_substring_not_found, "test_sl_string__replace_first_substring_not_found", 1127);
  run_test(test_sl_string__replace_first_empty_string_and_replace_string, "test_sl_string__replace_first_empty_string_and_replace_string", 1134);
  run_test(test_sl_string__replace_last_successful, "test_sl_string__replace_last_successful", 1140);
  run_test(test_sl_string__replace_last_null_params, "test_sl_string__replace_last_null_params", 1147);
  run_test(test_sl_string__replace_last_substring_not_found, "test_sl_string__replace_last_substring_not_found", 1157);
  run_test(test_sl_string__replace_all_successful, "test_sl_string__replace_all_successful", 1164);
  run_test(test_sl_string__replace_all_null_params, "test_sl_string__replace_all_null_params", 1171);
  run_test(test_sl_string__replace_all_substring_not_found, "test_sl_string__replace_all_substring_not_found", 1181);
  run_test(test_sl_string__replace_all_double_slash_with_slash, "test_sl_string__replace_all_double_slash_with_slash", 1188);

  return UnityEnd();
}
